### ISSUE TITLE
Error encountered during startup 

### ISSUE THREAD

**Issue by balaji-venkatesh** [comp500/skypecord#1]
It seems that I am having an issue connecting to the Discord API.  The command-line output indicates that `Bots cannot use this endpoint`. According to [this issue thread](https://github.com/izy521/discord.io/issues/109) on another repository, this is a fixable issue that has arised from a new update. [This ](https://github.com/izy521/discord.io/commit/228740bc28b1ab271fbec521d295a233ab217fe0)seems to be what fixed it. However, I'm not quite sure, as I have no idea what any of the code does.

Here is the complete output: 
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Balaji> cd D:\Github\skypecord\
PS D:\Github\skypecord> node .\index.js
[tokenredacted]
Discord client ready!
{ Error: 400 BAD REQUEST on POST /users/@me/channels

{"code": 20001, "message": "Bots cannot use this endpoint"}
    at IncomingMessage._respStream.on.once (D:\Github\skypecord\node_modules\eris\lib\rest\RequestHandler.js:233:39)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  resp:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: { end: [Function: responseOnEnd], data: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'discordapp.com',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 363,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1992,
        _destroyed: false,
        [Symbol(asyncId)]: 99,
        [Symbol(bytesRead)]: 587,
        [Symbol(asyncId)]: 106,
        [Symbol(triggerAsyncId)]: 102 },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'discordapp.com',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 363,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1992,
        _destroyed: false,
        [Symbol(asyncId)]: 99,
        [Symbol(bytesRead)]: 587,
        [Symbol(asyncId)]: 106,
        [Symbol(triggerAsyncId)]: 102 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { date: 'Mon, 28 May 2018 01:52:31 GMT',
        'content-type': 'application/json',
        'content-length': '59',
        connection: 'close',
        'set-cookie': [Array],
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        via: '1.1 google',
        'alt-svc': 'clear',
        'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
        server: 'cloudflare',
        'cf-ray': '421d1515ee085534-ORD' },
     rawHeaders:
      [ 'Date',
        'Mon, 28 May 2018 01:52:31 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '59',
        'Connection',
        'close',
        'Set-Cookie',
        '__cfduid=d7b4dc8657d99786d323b8bbff3bb52591527472351; expires=Tue, 28-May-19 01:52:31 GMT; path=/; domain=.discordapp.com; HttpOnly',
        'Strict-Transport-Security',
        'max-age=31536000; includeSubDomains',
        'Via',
        '1.1 google',
        'Alt-Svc',
        'clear',
        'Expect-CT',
        'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
        'Server',
        'cloudflare',
        'CF-RAY',
        '421d1515ee085534-ORD' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 400,
     statusMessage: 'BAD REQUEST',
     client:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'discordapp.com',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 363,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1992,
        _destroyed: false,
        [Symbol(asyncId)]: 99,
        [Symbol(bytesRead)]: 587,
        [Symbol(asyncId)]: 106,
        [Symbol(triggerAsyncId)]: 102 },
     _consuming: true,
     _dumped: false,
     req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 46,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /api/v6/users/@me/channels HTTP/1.1\r\nUser-Agent: DiscordBot (https://github.com/abalabahaha/eris, 0.7.2)\r\nAccept-Encoding: gzip,deflate\r\nAuthorization: Bot [tokenredacted]\r\nContent-Type: application/json\r\nHost: discordapp.com\r\nConnection: close\r\nContent-Length: 46\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/v6/users/@me/channels',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: [Function: emitTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     read: [Function] },
  response: '{"code": 20001, "message": "Bots cannot use this endpoint"}',
  req:
   ClientRequest {
     domain: null,
     _events:
      { abort: [Object],
        aborted: [Object],
        error: [Object],
        timeout: [Object],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 5,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 46,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'discordapp.com',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 363,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1992,
        _destroyed: false,
        [Symbol(asyncId)]: 99,
        [Symbol(bytesRead)]: 587,
        [Symbol(asyncId)]: 106,
        [Symbol(triggerAsyncId)]: 102 },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'discordapp.com',
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 363,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1992,
        _destroyed: false,
        [Symbol(asyncId)]: 99,
        [Symbol(bytesRead)]: 587,
        [Symbol(asyncId)]: 106,
        [Symbol(triggerAsyncId)]: 102 },
     _header: 'POST /api/v6/users/@me/channels HTTP/1.1\r\nUser-Agent: DiscordBot (https://github.com/abalabahaha/eris, 0.7.2)\r\nAccept-Encoding: gzip,deflate\r\nAuthorization: Bot [tokenredacted]\r\nContent-Type: application/json\r\nHost: discordapp.com\r\nConnection: close\r\nContent-Length: 46\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '/api/v6/users/@me/channels',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 400,
        statusMessage: 'BAD REQUEST',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        read: [Function] },
     aborted: undefined,
     timeoutCb: [Function: emitTimeout],
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     [Symbol(outHeadersKey)]:
      { 'user-agent': [Array],
        'accept-encoding': [Array],
        authorization: [Array],
        'content-type': [Array],
        host: [Array] } } }
error
Failed to find t inside.

```

**Comment by comp500** [comment]
This won't be affected by discord.io, as this bot uses Eris rather than discord.io. I don't think those issues are related, but it could be due to the token not being input properly.

You could also try running `npm install` again, to ensure that the correct version of Eris is used.

It seemed to work fine when I tried it, so it's probably an incorrect token. Make sure you use the token for your bot user, as follows: 
![image](https://user-images.githubusercontent.com/1138417/40615866-8d60e0e6-6280-11e8-9739-f7e83b7e9be7.png)
And the user ID for the bot in the user list (with Developer Mode enabled): 
![image](https://user-images.githubusercontent.com/1138417/40615911-b42a6c88-6280-11e8-9f0d-b4f1461c445e.png)

I've pushed a package-lock.json file, so that dependency versions are correct.
